rabbitmq:
  build: docker/rabbitmq

analyzer:
  build: analyzer
  entrypoint: npm run daemon
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/tmp:/tmp"
  environment:
    - AMQP_HOST=continuousqa_rabbitmq_1
    - ARTIFACT_ENDPOINT=http://continuousqa_nginx_1/artifacts

mongodb:
  build: docker/mongodb

nginx:
  build: docker/nginx
  ports:
    - "80:80"

build-api:
  build: build-api
  environment:
    - AMQP_HOST=continuousqa_rabbitmq_1
    - MONGO_URI=mongodb://continuousqa_mongodb_1:27017

artifact-api:
  build: artifact-api
  expose: ['8000']
  environment:
    - MONGO_HOST_PORT=continuousqa_mongodb_1:27017

front:
  build: front
  volumes:
    - "./front/:/var/www/"
