rabbitmq:
  build: docker/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"

analyzer:
  build: analyzer
  entrypoint: npm run daemon
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/tmp:/tmp"
  environment:
    - AMQP_HOST=continuousqa_rabbitmq_1

mongodb:
  build: docker/mongodb
  ports:
    - "27017:27017"

nginx:
  build: docker/nginx
  ports:
    - "80:80"
  volumes_from:
    - front

build-api:
  build: build-api
  environment:
    - AMQP_HOST=continuousqa_rabbitmq_1
    - MONGO_URI=mongodb://continuousqa_mongodb_1:27017
  volumes:
    - "./build-api/:/usr/src/app/"

artifact-api:
  build: artifact-api
  expose: ['8000']
  environment:
    - MONGO_HOST_PORT=continuousqa_mongodb_1:27017

front:
  build: front
  volumes:
    - "./front/:/var/www/"
