version: '2'

services:
  logstash:
    build: logstash
    cpu_quota: 100000
    cpu_shares: 512

  mongodb:
    build: mongodb

  nginx:
    build: nginx
    ports:
      - "80:80"

  rabbitmq:
    build: rabbitmq

  vault:
    build: vault
    command: "server"
    cap_add:
      - IPC_LOCK
