version: '2'

services:
  rabbitmq:
    build: rabbitmq

  mongodb:
    build: mongodb

  nginx:
    build: nginx
    ports:
      - "80:80"

  build-api:
    build: ../build-api
    env_file: ../build-api/.env

  artifact-api:
    build: ../artifact-api
    env_file: ../artifact-api/.env
    expose: ['8000']
    environment:
      - MONGO_HOST_PORT=continuousqa_mongodb_1:27017

  front:
    build: ../front
    volumes:
      - "../front/web/:/var/www/app/"

  user-api:
    build: ../user-api
    expose: ['3000']
    env_file: ../user-api/.env
    environment:
      - AMQP_HOST=continuousqa_rabbitmq_1
      - MONGO_URI=mongodb://continuousqa_mongodb_1:27017

  runner-api:
    build: ../runner-api
    expose: ['8000']
    env_file: ../runner-api/.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  runner-gc:
    build: ../runner-gc
    env_file: ../runner-gc/.env

  runner-consumer:
    build: ../runner-consumer
    env_file: ../runner-consumer/.env

  docker-events:
    build: ../docker-events
    env_file: ../docker-events/.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
