version: '2'

services:
  rabbitmq:
    build: rabbitmq

  mongodb:
    build: mongodb

  nginx:
    build: nginx
    ports:
      - "80:80"

  build-api:
    build: ../services/build-api
    env_file: ../services/build-api/.env

  artifact-api:
    build: ../services/artifact-api
    env_file: ../services/artifact-api/.env
    expose: ['8000']
    environment:
      - MONGO_HOST_PORT=continuousqa_mongodb_1:27017

  front:
    build: ../services/front
    volumes:
      - "../services/front/web/:/var/www/app/"

  user-api:
    build: ../services/user-api
    expose: ['3000']
    env_file: ../services/user-api/.env
    environment:
      - AMQP_HOST=continuousqa_rabbitmq_1
      - MONGO_URI=mongodb://continuousqa_mongodb_1:27017

  runner-api:
    build: ../services/runner-api
    expose: ['8000']
    env_file: ../services/runner-api/.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  runner-gc:
    build: ../services/runner-gc
    env_file: ../services/runner-gc/.env

  build-consumer:
    build: ../services/build-consumer
    env_file: ../services/build-consumer/.env

  docker-events:
    build: ../services/docker-events
    env_file: ../services/docker-events/.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
