rabbitmq:
  build: rabbitmq

mongodb:
  build: mongodb

nginx:
  build: nginx
  ports:
    - "80:80"

build-api:
  build: ../build-api
  environment:
    - AMQP_HOST=continuousqa_rabbitmq_1
    - MONGO_URI=mongodb://continuousqa_mongodb_1:27017

artifact-api:
  build: ../artifact-api
  expose: ['8000']
  environment:
    - MONGO_HOST_PORT=continuousqa_mongodb_1:27017

front:
  build: ../front
  volumes:
    - "../front/web/:/var/www/app/"

user-api:
  build: ../user-api
  expose: ['3000']
  env_file: ../user-api/.env
  environment:
    - AMQP_HOST=continuousqa_rabbitmq_1
    - MONGO_URI=mongodb://continuousqa_mongodb_1:27017

runner-api:
  build: ../runner-api
  expose: ['8000']
  env_file: ../runner-api/.env
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

docker-events:
  build: ../docker-events
  env_file: ../docker-events/.env
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
