version: '2'

services:
  docs:
    build:
      context: ..
      dockerfile: docker/docs/Dockerfile
    restart: never
    command: ["dev-generate-docs"]
    volumes:
      - "..:/usr/src/app"
      - "../docs:/usr/src/app/docs"

  logstash:
    extends:
      file: ../docker/common.yml
      service: logstash
    depends_on: [mongodb]
    volumes:
      - "../docker/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf"

  mongodb:
    extends:
      file: ../docker/common.yml
      service: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "../services/build-api/fixtures/:/fixtures/build-api/"
      - "../services/log-api/fixtures/:/fixtures/log-api/"
      - "../services/pipeline-api/fixtures/:/fixtures/pipeline-api/"
      - "../services/plugin-api/fixtures/:/fixtures/plugin-api/"
      - "..//dumps/:/dumps/"

  nginx:
    extends:
      file: ../docker/common.yml
      service: nginx
    volumes_from:
      - front
      - docs
    volumes:
      - "../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "../docs/:/usr/src/app/docs"

  rabbitmq:
    extends:
      file: ../docker/common.yml
      service: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
