rabbitmq:
  extends:
    file: common.yml
    service: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"

mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
    - "27017:27017"

nginx:
  extends:
    file: common.yml
    service: nginx
  volumes_from:
    - front
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

build-api:
  extends:
    file: common.yml
    service: build-api
  volumes:
    - "../build-api/:/usr/src/app/"

artifact-api:
  extends:
    file: common.yml
    service: artifact-api
  volumes:
    - "../artifact-api/:/usr/src/app/"

front:
  extends:
    file: common.yml
    service: front

user-api:
  extends:
    file: common.yml
    service: user-api
  command: dev-app
  volumes:
    - "../user-api/:/usr/src/app/"

runner-api:
  extends:
    file: common.yml
    service: runner-api
  command: dev-app
  volumes:
    - "../runner-api/:/usr/src/app/"

docker-events:
  extends:
    file: common.yml
    service: docker-events
  command: dev-app
  volumes:
    - "../docker-events/:/usr/src/app/"
